---
author: 'ulker'
description: ''
email: 'ulkerfurkan@gmail.com'
url: ''
domain: ''
intro: ''
googleanalytics: ''
googleplus: ''
brand: default
landslide: /usr/bin/landslide
css: _/default.css
js: _/default.js
theme: light
indextemplate: _/index.erb
foliotemplate: _/default.erb
